from __future__ import annotations

from app.domain.material_ontology import WASTE_DISPOSAL_METHOD_SYNONYMS, WASTE_MATERIAL_SYNONYMS


VEHICLE_FACTOR_VALUE_ALIASES = {
    "fuel_type": {
        "petrol": ("petrol", "gasoline"),
        "diesel": ("diesel",),
        "electric": ("electric", "electricity", "battery electric", "bev"),
        "hybrid": ("hybrid", "hev"),
    },
    "vehicle_size": {
        "small": ("small",),
        "medium": ("medium",),
        "large": ("large",),
    },
    "vehicle_class": {
        "suv": ("suv", "sport utility"),
        "ute": ("ute", "pickup"),
        "van": ("van",),
        "sedan": ("sedan",),
        "hatchback": ("hatchback",),
        "wagon": ("wagon",),
        "coupe": ("coupe",),
    },
}

VEHICLE_FACTOR_VALUE_CONFLICTS = {
    "vehicle_size": {
        "medium": ("lower medium", "upper medium"),
    },
}

FLIGHT_FACTOR_VALUE_ALIASES = {
    "route_type": {
        "domestic": ("domestic",),
        "international": ("international",),
    },
    "passenger_class": {
        "average": ("national average", "average passenger", "class na"),
        "economy": ("economy",),
        "premium_economy": ("premium economy",),
        "business": ("business",),
        "first": ("first class",),
    },
    "rf_effect": {
        "included": ("rf included", "with rf effect"),
        "excluded": ("rf excluded", "without rf effect"),
    },
    "distance_band": {
        "short_haul": ("short haul",),
        "long_haul": ("long haul",),
    },
}

TRAIN_FACTOR_VALUE_ALIASES = {
    "fuel_type": VEHICLE_FACTOR_VALUE_ALIASES["fuel_type"],
    "route_type": {
        "commuter": ("commuter rail",),
        "tram": ("light rail and tram", "tram", "streetcar"),
        "metro": ("metropolitan railway", "urban passenger"),
        "subway": ("subway",),
        "underground": ("underground",),
        "intercity": ("intercity", "long distance"),
        "high_speed": ("high speed", "tgv"),
    },
}


ENERGY_TAXONOMY = {
    "electricity_use": {
        "category": "energy",
        "keywords": ("electricity", "power", "kwh", "kilowatt hour"),
        "required_quantity_dimensions": ("energy",),
        "supporting_quantity_dimensions": (),
        "derivation_rules": (),
        "parameter_builder": "energy",
        "fallback_factor_key": "energy.au_electricity",
        "climatiq_factor_query": "electricity consumption Australia",
        "factor_source": "climatiq",
        "compatible_unit_types": ("Energy",),
        "factor_match_terms": ("electricity", "grid", "residual mix"),
        "factor_preferred_terms": ("residual mix",),
        "factor_identity_fields": (),
        "factor_trait_fields": (),
        "default_assumptions": ("region.default_au_electricity",),
    },
    "space_heater_use": {
        "category": "energy",
        "keywords": ("heater", "space heater", "heating"),
        "required_quantity_dimensions": ("energy",),
        "supporting_quantity_dimensions": ("duration", "power"),
        "derivation_rules": (
            "power + duration -> energy",
            "duration + default_power -> energy",
        ),
        "parameter_builder": "energy",
        "fallback_factor_key": "energy.au_electricity",
        "climatiq_factor_query": "electricity consumption Australia",
        "factor_source": "climatiq",
        "compatible_unit_types": ("Energy",),
        "factor_match_terms": ("electricity", "grid", "residual mix"),
        "factor_preferred_terms": ("residual mix",),
        "factor_identity_fields": (),
        "factor_trait_fields": (),
        "default_assumptions": (
            "space_heater.default_power",
            "region.default_au_electricity",
        ),
    },
    "natural_gas_use": {
        "category": "energy",
        "keywords": ("natural gas", "gas stove", "gas cooktop"),
        "required_quantity_dimensions": (),
        "supporting_quantity_dimensions": ("duration",),
        "derivation_rules": (),
        "parameter_builder": "energy",
        "fallback_factor_key": None,
        "estimate_policy": "unresolved",
        "detection_patterns": (
            r"\b(?:used?|cooked|cooking|heated?)\b[^,.;]{0,60}\b(?:natural\s+gas|gas\s+(?:stove|cooktop|oven))\b",
            r"\bnatural\s+gas\b[^,.;]{0,60}\b(?:cook|cooking|heating)\b",
        ),
        "default_assumptions": (),
    },
    "cooking_appliance_use": {
        "category": "energy",
        "keywords": ("oven", "stove", "cooktop", "stovetop"),
        "required_quantity_dimensions": (),
        "supporting_quantity_dimensions": ("duration",),
        "derivation_rules": (),
        "parameter_builder": "energy",
        "fallback_factor_key": None,
        "estimate_policy": "unresolved",
        "detection_patterns": (
            r"\b(?:cook(?:ed|ing)?|used?|ran|turned\s+on)\b[^,.;]{0,60}\b(?:oven|cooktop|stove|stovetop)\b",
        ),
        "default_assumptions": (),
    },
    "hot_water_use": {
        "category": "energy",
        "keywords": ("hot shower", "hot bath", "hot water"),
        "required_quantity_dimensions": (),
        "supporting_quantity_dimensions": ("duration",),
        "derivation_rules": (),
        "parameter_builder": "energy",
        "fallback_factor_key": None,
        "estimate_policy": "unresolved",
        "detection_patterns": (
            r"\b(?:hot\s+(?:shower|bath|water)|shower(?:ed|ing)?\b[^,.;]{0,40}\bhot\s+water)\b",
        ),
        "default_assumptions": (),
    },
    "generic_energy_use": {
        "category": "energy",
        "keywords": (
            "thing",
            "device",
            "appliance",
            "equipment",
            "phone",
            "laptop",
            "tablet",
            "battery",
            "charger",
        ),
        "required_quantity_dimensions": (),
        "supporting_quantity_dimensions": ("duration",),
        "derivation_rules": (),
        "parameter_builder": "energy",
        "fallback_factor_key": None,
        "estimate_policy": "unresolved",
        "detection_patterns": (
            r"\b(?:used?|ran|operated|turned\s+on)\b[^,.;]{0,40}\b(?:thing|device|appliance|equipment)\b",
            r"\b(?:charged?|charging|plugged\s+in)\b[^,.;]{0,40}\b(?:phone|laptop|tablet|battery|device)\b",
            r"\b(?:watched?|used?|ran|turned\s+on)\b[^,.;]{0,40}\b(?:tv|television|monitor|computer)\b",
            r"\b(?:gaming|played?|playing)\b[^,.;]{0,50}\b(?:on\s+)?(?:my\s+)?(?:pc|computer|desktop)\b",
        ),
        "default_assumptions": (),
    },
}

TRANSPORT_TAXONOMY = {
    "car_ride": {
        "category": "transport",
        "keywords": ("drive", "drove", "driving", "ride", "trip", "commute", "car"),
        "mode_synonyms": ("drive", "drove", "driving", "ride", "trip", "commute", "commuted", "car"),
        "required_quantity_dimensions": ("distance",),
        "supporting_quantity_dimensions": ("duration", "number"),
        "derivation_rules": (),
        "parameter_builder": "transport",
        "fallback_factor_key": "transport.road_distance",
        "climatiq_factor_query": "passenger car distance",
        "factor_source": "climatiq",
        "estimate_policy": "climatiq_vehicle_distance",
        "compatible_unit_types": ("Distance",),
        "factor_match_terms": ("car",),
        "factor_required_terms": ("car",),
        "factor_preferred_terms": ("passenger vehicle", "business travel"),
        "factor_excluded_terms": ("managed assets", "taxi", "cab"),
        "factor_identity_fields": ("vehicle_description",),
        "factor_trait_fields": ("fuel_type", "vehicle_size", "vehicle_class"),
        "factor_required_authoritative_traits": ("fuel_type",),
        "factor_value_aliases": VEHICLE_FACTOR_VALUE_ALIASES,
        "factor_value_conflicts": VEHICLE_FACTOR_VALUE_CONFLICTS,
        "default_assumptions": ("vehicle.generic_car.default_petrol_medium",),
    },
    "bus_ride": {
        "category": "transport",
        "keywords": ("bus", "coach"),
        "mode_synonyms": ("bus", "coach"),
        "required_quantity_dimensions": ("distance",),
        "supporting_quantity_dimensions": (),
        "derivation_rules": (),
        "parameter_builder": "transport",
        "fallback_factor_key": "transport.public_passenger_distance",
        "climatiq_factor_query": "passenger bus distance",
        "factor_source": "climatiq",
        "estimate_policy": "climatiq_distance",
        "compatible_unit_types": ("PassengerOverDistance", "Distance"),
        "factor_match_terms": ("bus",),
        "factor_required_terms": ("bus", "coach"),
        "factor_preferred_terms": ("passenger vehicle", "average", "fuel source na"),
        "factor_identity_fields": (),
        "factor_trait_fields": ("fuel_type",),
        "factor_required_authoritative_traits": ("fuel_type",),
        "factor_value_aliases": VEHICLE_FACTOR_VALUE_ALIASES,
        "factor_value_conflicts": VEHICLE_FACTOR_VALUE_CONFLICTS,
        "default_assumptions": (),
    },
    "train_ride": {
        "category": "transport",
        "keywords": ("train", "rail", "tram", "subway", "metro", "underground"),
        "mode_synonyms": (
            "train",
            "rail",
            "tram",
            "light rail",
            "subway",
            "metro",
            "underground",
            "tgv",
        ),
        "entity_value_synonyms": {
            "route_type": {
                "commuter": ("commuter rail", "commuter train"),
                "tram": ("tram", "light rail", "streetcar"),
                "metro": ("metro",),
                "subway": ("subway",),
                "underground": ("underground",),
                "intercity": ("intercity", "long distance"),
                "high_speed": ("high speed", "tgv"),
            },
        },
        "required_quantity_dimensions": ("distance",),
        "supporting_quantity_dimensions": (),
        "derivation_rules": (),
        "parameter_builder": "transport",
        "fallback_factor_key": "transport.public_passenger_distance",
        "climatiq_factor_query": "passenger train distance",
        "factor_source": "climatiq",
        "estimate_policy": "climatiq_distance",
        "compatible_unit_types": ("PassengerOverDistance",),
        "factor_match_terms": ("passenger", "train"),
        "factor_required_terms": ("train", "rail"),
        "factor_preferred_terms": ("route type na", "fuel source na"),
        "factor_identity_fields": (),
        "factor_trait_fields": ("fuel_type", "route_type"),
        "factor_required_authoritative_traits": ("fuel_type", "route_type"),
        "factor_value_aliases": TRAIN_FACTOR_VALUE_ALIASES,
        "factor_value_conflicts": VEHICLE_FACTOR_VALUE_CONFLICTS,
        "default_assumptions": (),
    },
    "flight": {
        "category": "transport",
        "keywords": ("flight", "flew", "plane"),
        "mode_synonyms": ("flight", "flew", "plane", "aeroplane", "airplane"),
        "required_quantity_dimensions": ("distance",),
        "supporting_quantity_dimensions": (),
        "derivation_rules": (),
        "parameter_builder": "transport",
        "fallback_factor_key": None,
        "climatiq_factor_query": "passenger flight distance",
        "factor_source": "climatiq",
        "estimate_policy": "climatiq_distance",
        "compatible_unit_types": ("PassengerOverDistance", "Distance"),
        "factor_match_terms": ("flight", "aircraft", "air travel"),
        "factor_required_terms": ("flight", "air travel"),
        "factor_preferred_terms": ("passenger",),
        "factor_identity_fields": (),
        "factor_trait_fields": (
            "route_type",
            "passenger_class",
            "rf_effect",
            "distance_band",
        ),
        "factor_required_authoritative_traits": ("route_type", "passenger_class"),
        "factor_value_aliases": FLIGHT_FACTOR_VALUE_ALIASES,
        "factor_value_conflicts": {},
        "default_assumptions": (),
    },
    "rideshare": {
        "category": "transport",
        "keywords": ("uber", "rideshare", "taxi"),
        "mode_synonyms": ("uber", "rideshare", "taxi", "cab"),
        "required_quantity_dimensions": ("distance",),
        "supporting_quantity_dimensions": ("duration",),
        "derivation_rules": (),
        "parameter_builder": "transport",
        "fallback_factor_key": "transport.road_distance",
        "climatiq_factor_query": "taxi passenger car distance",
        "factor_source": "climatiq",
        "estimate_policy": "climatiq_vehicle_distance",
        "compatible_unit_types": ("PassengerOverDistance", "Distance"),
        "factor_match_terms": ("taxi", "cab"),
        "factor_required_terms": ("taxi", "cab"),
        "factor_preferred_terms": ("passenger vehicle", "average", "fuel source na"),
        "factor_identity_fields": ("vehicle_description",),
        "factor_trait_fields": ("fuel_type", "vehicle_size", "vehicle_class"),
        "factor_required_authoritative_traits": ("fuel_type",),
        "factor_value_aliases": VEHICLE_FACTOR_VALUE_ALIASES,
        "factor_value_conflicts": VEHICLE_FACTOR_VALUE_CONFLICTS,
        "default_assumptions": ("vehicle.generic_car.default_petrol_medium",),
    },
    "bicycle_ride": {
        "category": "transport",
        "keywords": ("bike", "bicycle", "cycling"),
        "mode_synonyms": ("bike", "bicycle", "cycling", "cycled"),
        "required_quantity_dimensions": ("distance",),
        "supporting_quantity_dimensions": (),
        "derivation_rules": (),
        "parameter_builder": "transport",
        "fallback_factor_key": None,
        "estimate_policy": "operational_zero",
        "emissions_boundary": "No powered operational emissions estimated for personal cycling.",
        "default_assumptions": (),
    },
    "walking": {
        "category": "transport",
        "keywords": ("walk", "walking", "run", "running", "jogging"),
        "mode_synonyms": ("walk", "walked", "walking", "run", "ran", "running", "jog", "jogged", "jogging"),
        "required_quantity_dimensions": ("distance",),
        "supporting_quantity_dimensions": (),
        "derivation_rules": (),
        "parameter_builder": "transport",
        "fallback_factor_key": None,
        "estimate_policy": "operational_zero",
        "emissions_boundary": "No powered operational emissions estimated for walking.",
        "default_assumptions": (),
    },
    "generic_transport": {
        "category": "transport",
        "keywords": ("ferry", "tram", "scooter", "motorbike", "motorcycle"),
        "mode_synonyms": ("ferry", "tram", "scooter", "motorbike", "motorcycle"),
        "required_quantity_dimensions": ("distance",),
        "supporting_quantity_dimensions": (),
        "derivation_rules": (),
        "parameter_builder": "transport",
        "fallback_factor_key": None,
        "estimate_policy": "unresolved",
        "default_assumptions": (),
    },
}

GOODS_SERVICES_TAXONOMY = {
    "coffee_purchase": {
        "category": "goods_services",
        "keywords": ("coffee", "coffees", "flat white", "latte", "cappuccino"),
        "purchase_verbs": (
            "buy",
            "grabbed",
            "bought",
            "purchased",
            "ordered",
            "had",
            "got",
            "picked up",
        ),
        "product_synonyms": {
            "coffee": ("coffee", "coffees", "flat white", "flat whites"),
        },
        "unsupported_variant_terms": ("oat milk",),
        "required_quantity_dimensions": ("number",),
        "supporting_quantity_dimensions": ("money",),
        "parameter_builder": "goods_services",
        "fallback_factor_key": "goods.coffee_serving",
        "compatible_unit_types": ("Number", "Money"),
        "factor_match_terms": ("coffee", "beverage"),
        "factor_preferred_terms": ("serving", "cup"),
        "factor_identity_fields": ("product_class",),
        "factor_trait_fields": (),
        "default_assumptions": (),
        "pathways": {
            "coffee": {
                "required_dimension": "number",
                "calculation_unit": "item",
                "infer_singular_item": True,
                "boundary_note": "One prepared coffee beverage serving; add-ons are not separately modelled.",
            },
        },
    },
    "restaurant_meal": {
        "category": "goods_services",
        "keywords": (
            "burrito",
            "burger",
            "fries",
            "chips",
            "pizza",
            "sandwich",
            "meal",
            "takeaway",
            "takeout",
            "delivery app",
        ),
        "purchase_verbs": (
            "buy",
            "ordered",
            "bought",
            "had",
            "ate",
            "grabbed",
            "got",
            "picked up",
        ),
        "product_synonyms": {
            "beef_burrito": ("beef burrito", "beef burritos"),
            "burger": ("burger", "burgers", "hamburger", "hamburgers"),
            "fries": ("fries", "hot chips"),
            "pizza": ("pizza", "pizzas"),
            "sandwich": ("sandwich", "sandwiches"),
            "unspecified_takeaway": ("takeaway", "takeout", "delivery app", "restaurant", "restaurant meal"),
        },
        "required_quantity_dimensions": ("number",),
        "supporting_quantity_dimensions": (),
        "parameter_builder": "goods_services",
        "fallback_factor_key": "goods.beef_burrito_serving",
        "compatible_unit_types": ("Number",),
        "factor_match_terms": ("meal", "burrito", "beef"),
        "factor_preferred_terms": ("serving",),
        "factor_identity_fields": ("product_class",),
        "factor_trait_fields": (),
        "default_assumptions": (),
        "pathways": {
            "beef_burrito": {
                "required_dimension": "number",
                "calculation_unit": "item",
                "infer_singular_item": True,
                "fallback_factor_key": "goods.beef_burrito_serving",
                "boundary_note": "One beef burrito serving; delivery travel and separate drinks are excluded.",
            },
            "burger": {
                "required_dimension": "number",
                "calculation_unit": "item",
                "infer_singular_item": True,
                "fallback_factor_key": "goods.burger_serving",
                "boundary_note": "One burger serving; sides, drinks, and delivery travel are excluded.",
            },
            "fries": {
                "required_dimension": "number",
                "calculation_unit": "item",
                "infer_singular_item": True,
                "fallback_factor_key": "goods.fries_serving",
                "boundary_note": "One serving of fries or hot chips; delivery travel is excluded.",
            },
            "pizza": {
                "required_dimension": "number",
                "calculation_unit": "item",
                "infer_singular_item": True,
                "fallback_factor_key": "goods.pizza_serving",
                "boundary_note": "One pizza serving or item as described; delivery travel is excluded.",
            },
            "sandwich": {
                "required_dimension": "number",
                "calculation_unit": "item",
                "infer_singular_item": True,
                "fallback_factor_key": "goods.sandwich_serving",
                "boundary_note": "One sandwich serving; drinks and delivery travel are excluded.",
            },
        },
    },
    "food_purchase": {
        "category": "goods_services",
        "keywords": (
            "beef",
            "groceries",
            "grocery",
            "soft drink",
            "milk",
            "bread",
            "snack",
            "snacks",
            "food",
        ),
        "purchase_verbs": (
            "buy",
            "bought",
            "purchased",
            "ordered",
            "grabbed",
            "got",
            "picked up",
        ),
        "product_synonyms": {
            "beef": ("beef",),
            "groceries": ("groceries", "grocery"),
            "soft_drink": ("soft drink", "soft drinks", "soda"),
            "milk": ("milk", "milks"),
            "bread": ("bread", "loaf of bread", "bread loaf"),
            "snacks": ("snack", "snacks", "crisps", "chips"),
        },
        "required_quantity_dimensions": ("weight", "number"),
        "supporting_quantity_dimensions": ("money", "number"),
        "parameter_builder": "goods_services",
        "fallback_factor_key": "goods.beef_weight",
        "compatible_unit_types": ("Weight",),
        "factor_match_terms": ("food", "beef"),
        "factor_preferred_terms": ("weight",),
        "factor_identity_fields": ("product_class",),
        "factor_trait_fields": (),
        "default_assumptions": (),
        "pathways": {
            "beef": {
                "required_dimension": "weight",
                "calculation_unit": "kg",
                "infer_singular_item": False,
                "fallback_factor_key": "goods.beef_weight",
                "boundary_note": "Purchased beef mass only.",
            },
            "soft_drink": {
                "required_dimension": "number",
                "calculation_unit": "item",
                "infer_singular_item": True,
                "fallback_factor_key": "goods.soft_drink_serving",
                "boundary_note": "One soft drink serving; packaging and delivery travel are excluded.",
            },
            "milk": {
                "required_dimension": "number",
                "calculation_unit": "item",
                "infer_singular_item": True,
                "fallback_factor_key": "goods.milk_item",
                "boundary_note": "One retail milk item; exact container size is not inferred.",
            },
            "bread": {
                "required_dimension": "number",
                "calculation_unit": "item",
                "infer_singular_item": True,
                "fallback_factor_key": "goods.bread_item",
                "boundary_note": "One bread item or loaf; exact weight is not inferred.",
            },
            "snacks": {
                "required_dimension": "number",
                "calculation_unit": "item",
                "infer_singular_item": True,
                "fallback_factor_key": "goods.snack_serving",
                "boundary_note": "One snack item or serving; product mix remains approximate.",
            },
        },
    },
    "clothing_purchase": {
        "category": "goods_services",
        "keywords": ("shirt", "clothing", "shoes"),
        "parameter_builder": "goods_services",
        "estimate_policy": "unresolved",
        "default_assumptions": (),
    },
    "electronics_purchase": {
        "category": "goods_services",
        "keywords": ("laptop", "phone", "computer"),
        "parameter_builder": "goods_services",
        "estimate_policy": "unresolved",
        "default_assumptions": (),
    },
}

WASTE_TAXONOMY = {
    "recycling": {
        "category": "waste",
        "disposal_method": "recycling",
        "disposal_synonyms": WASTE_DISPOSAL_METHOD_SYNONYMS["recycling"],
        "material_synonyms": WASTE_MATERIAL_SYNONYMS,
        "required_quantity_dimensions": ("weight",),
        "parameter_builder": "waste",
        "compatible_unit_types": ("Weight",),
        "factor_match_terms": ("recycling",),
        "factor_identity_fields": ("material_class", "disposal_method"),
        "factor_trait_fields": (),
        "pathways": {
            "plastic": {"fallback_factor_key": "waste.recycling_plastic"},
            "cardboard": {"fallback_factor_key": "waste.recycling_cardboard"},
            "paper": {"fallback_factor_key": "waste.recycling_paper"},
            "glass": {"fallback_factor_key": "waste.recycling_glass"},
            "metal": {"fallback_factor_key": "waste.recycling_metal"},
        },
    },
    "composting": {
        "category": "waste",
        "disposal_method": "composting",
        "disposal_synonyms": WASTE_DISPOSAL_METHOD_SYNONYMS["composting"],
        "material_synonyms": WASTE_MATERIAL_SYNONYMS,
        "required_quantity_dimensions": ("weight",),
        "parameter_builder": "waste",
        "compatible_unit_types": ("Weight",),
        "factor_match_terms": ("compost", "food waste"),
        "factor_identity_fields": ("material_class", "disposal_method"),
        "factor_trait_fields": (),
        "pathways": {
            "food_waste": {"fallback_factor_key": "waste.composting_food"},
        },
    },
    "landfill_waste": {
        "category": "waste",
        "disposal_method": "landfill",
        "disposal_synonyms": WASTE_DISPOSAL_METHOD_SYNONYMS["landfill"],
        "material_synonyms": WASTE_MATERIAL_SYNONYMS,
        "required_quantity_dimensions": ("weight",),
        "parameter_builder": "waste",
        "compatible_unit_types": ("Weight",),
        "factor_match_terms": ("landfill", "waste"),
        "factor_identity_fields": ("material_class", "disposal_method"),
        "factor_trait_fields": (),
        "pathways": {
            "general_waste": {"fallback_factor_key": "waste.landfill_general"},
            "mixed_packaging": {"fallback_factor_key": "waste.landfill_general"},
            "plastic": {
                "fallback_factor_key": "waste.landfill_plastic",
            },
            "cardboard": {
                "fallback_factor_key": "waste.landfill_cardboard",
            },
            "paper": {
                "fallback_factor_key": "waste.landfill_paper",
            },
            "food_waste": {
                "fallback_factor_key": "waste.landfill_food",
            },
        },
    },
}

NON_ESTIMATED_TAXONOMY = {
    "personal_activity": {
        "category": "goods_services",
        "keywords": ("read", "reading", "study", "studied", "studying"),
        "required_quantity_dimensions": (),
        "supporting_quantity_dimensions": ("duration",),
        "derivation_rules": (),
        "parameter_builder": None,
        "fallback_factor_key": None,
        "estimate_policy": "not_estimated",
        "emissions_boundary": (
            "No direct operational emissions estimated for reading or studying "
            "without a specified energy or purchased-goods activity."
        ),
        "detection_patterns": (
            r"\b(?:read|reading)\b[^,.;]{0,40}\b(?:book|novel)\b",
            r"\bstud(?:y|ied|ying)\b",
        ),
        "default_assumptions": (),
    },
}

ACTIVITY_TAXONOMY = {
    **ENERGY_TAXONOMY,
    **TRANSPORT_TAXONOMY,
    **GOODS_SERVICES_TAXONOMY,
    **WASTE_TAXONOMY,
    **NON_ESTIMATED_TAXONOMY,
}
