from __future__ import annotations


ENERGY_TAXONOMY = {
    "electricity_use": {
        "category": "energy",
        "keywords": ("electricity", "power", "kwh", "kilowatt hour"),
        "required_quantity_dimensions": ("energy",),
        "supporting_quantity_dimensions": (),
        "derivation_rules": (),
        "parameter_builder": "energy",
        "fallback_factor_key": None,
        "climatiq_factor_query": "electricity consumption Australia",
        "factor_source": "climatiq",
        "default_assumptions": ("region.default_au_electricity",),
    },
    "space_heater_use": {
        "category": "energy",
        "keywords": ("heater", "space heater", "heating"),
        "required_quantity_dimensions": ("energy",),
        "supporting_quantity_dimensions": ("duration", "power"),
        "derivation_rules": (
            "power + duration -> energy",
            "duration + default_power -> energy",
        ),
        "parameter_builder": "energy",
        "fallback_factor_key": None,
        "climatiq_factor_query": "electricity consumption Australia",
        "factor_source": "climatiq",
        "default_assumptions": (
            "space_heater.default_power",
            "region.default_au_electricity",
        ),
    },
}

TRANSPORT_TAXONOMY = {
    "car_ride": {
        "category": "transport",
        "keywords": ("drive", "drove", "driving", "ride", "trip", "commute", "car"),
        "mode_synonyms": ("drive", "drove", "driving", "ride", "trip", "commute", "commuted", "car"),
        "required_quantity_dimensions": ("distance",),
        "supporting_quantity_dimensions": ("duration", "number"),
        "derivation_rules": (),
        "parameter_builder": "transport",
        "fallback_factor_key": None,
        "climatiq_factor_query": "passenger car distance",
        "factor_source": "climatiq",
        "estimate_policy": "climatiq_vehicle_distance",
        "default_assumptions": ("vehicle.generic_car.default_petrol_medium",),
    },
    "bus_ride": {
        "category": "transport",
        "keywords": ("bus", "coach"),
        "mode_synonyms": ("bus", "coach"),
        "required_quantity_dimensions": ("distance",),
        "supporting_quantity_dimensions": (),
        "derivation_rules": (),
        "parameter_builder": "transport",
        "fallback_factor_key": None,
        "climatiq_factor_query": "passenger bus distance",
        "factor_source": "climatiq",
        "estimate_policy": "climatiq_distance",
        "default_assumptions": (),
    },
    "train_ride": {
        "category": "transport",
        "keywords": ("train", "rail"),
        "mode_synonyms": ("train", "rail"),
        "required_quantity_dimensions": ("distance",),
        "supporting_quantity_dimensions": (),
        "derivation_rules": (),
        "parameter_builder": "transport",
        "fallback_factor_key": None,
        "climatiq_factor_query": "passenger train distance",
        "factor_source": "climatiq",
        "estimate_policy": "climatiq_distance",
        "default_assumptions": (),
    },
    "flight": {
        "category": "transport",
        "keywords": ("flight", "flew", "plane"),
        "mode_synonyms": ("flight", "flew", "plane", "aeroplane", "airplane"),
        "required_quantity_dimensions": ("distance",),
        "supporting_quantity_dimensions": (),
        "derivation_rules": (),
        "parameter_builder": "transport",
        "fallback_factor_key": None,
        "climatiq_factor_query": "passenger flight distance",
        "factor_source": "climatiq",
        "estimate_policy": "unresolved",
        "default_assumptions": (),
    },
    "rideshare": {
        "category": "transport",
        "keywords": ("uber", "rideshare", "taxi"),
        "mode_synonyms": ("uber", "rideshare", "taxi", "cab"),
        "required_quantity_dimensions": ("distance",),
        "supporting_quantity_dimensions": ("duration",),
        "derivation_rules": (),
        "parameter_builder": "transport",
        "fallback_factor_key": None,
        "climatiq_factor_query": "taxi passenger car distance",
        "factor_source": "climatiq",
        "estimate_policy": "climatiq_vehicle_distance",
        "default_assumptions": ("vehicle.generic_car.default_petrol_medium",),
    },
    "bicycle_ride": {
        "category": "transport",
        "keywords": ("bike", "bicycle", "cycling"),
        "mode_synonyms": ("bike", "bicycle", "cycling", "cycled"),
        "required_quantity_dimensions": ("distance",),
        "supporting_quantity_dimensions": (),
        "derivation_rules": (),
        "parameter_builder": "transport",
        "fallback_factor_key": None,
        "estimate_policy": "operational_zero",
        "emissions_boundary": "No powered operational emissions estimated for personal cycling.",
        "default_assumptions": (),
    },
    "walking": {
        "category": "transport",
        "keywords": ("walk", "walking"),
        "mode_synonyms": ("walk", "walked", "walking"),
        "required_quantity_dimensions": ("distance",),
        "supporting_quantity_dimensions": (),
        "derivation_rules": (),
        "parameter_builder": "transport",
        "fallback_factor_key": None,
        "estimate_policy": "operational_zero",
        "emissions_boundary": "No powered operational emissions estimated for walking.",
        "default_assumptions": (),
    },
    "generic_transport": {
        "category": "transport",
        "keywords": ("ferry", "tram", "scooter", "motorbike", "motorcycle"),
        "mode_synonyms": ("ferry", "tram", "scooter", "motorbike", "motorcycle"),
        "required_quantity_dimensions": ("distance",),
        "supporting_quantity_dimensions": (),
        "derivation_rules": (),
        "parameter_builder": "transport",
        "fallback_factor_key": None,
        "estimate_policy": "unresolved",
        "default_assumptions": (),
    },
}

ACTIVITY_TAXONOMY = {
    **ENERGY_TAXONOMY,
    **TRANSPORT_TAXONOMY,
}
