from __future__ import annotations

from dataclasses import dataclass

from app.domain.models import Assumption


@dataclass(frozen=True)
class FallbackFactor:
    """Maintained local coefficient used only when Climatiq cannot estimate."""

    key: str
    name: str
    category: str
    dimension: str
    amount_parameter: str
    unit_parameter: str
    unit: str
    kg_co2e_per_unit: float
    confidence: float
    source_reference: str

    def assumption(self) -> Assumption:
        return Assumption(
            code=f"fallback_factor.{self.key}",
            message=(
                f"Used local fallback factor {self.name} "
                f"({self.kg_co2e_per_unit:g} kg CO2e/{self.unit}) because "
                "no successful compatible Climatiq estimate was available."
            ),
            source="fallback",
            confidence_impact=-0.25,
        )


# These bootstrap coefficients retain the existing local fallback boundary from
# V1 while V2 makes its use visible. They are generic estimates, not model-level
# or route-specific accounting factors.
LOCAL_FALLBACK_FACTORS = {
    "energy.au_electricity": FallbackFactor(
        key="energy.au_electricity",
        name="generic electricity energy",
        category="energy",
        dimension="energy",
        amount_parameter="energy",
        unit_parameter="energy_unit",
        unit="kWh",
        kg_co2e_per_unit=0.4,
        confidence=0.55,
        source_reference="Existing CarbonCoach V1 local energy fallback coefficient.",
    ),
    "transport.road_distance": FallbackFactor(
        key="transport.road_distance",
        name="generic road transport distance",
        category="transport",
        dimension="distance",
        amount_parameter="distance",
        unit_parameter="distance_unit",
        unit="km",
        kg_co2e_per_unit=0.18,
        confidence=0.50,
        source_reference="Existing CarbonCoach V1 local transport distance coefficient.",
    ),
    "transport.public_passenger_distance": FallbackFactor(
        key="transport.public_passenger_distance",
        name="generic passenger transport distance",
        category="transport",
        dimension="distance",
        amount_parameter="distance",
        unit_parameter="distance_unit",
        unit="km",
        kg_co2e_per_unit=0.09,
        confidence=0.50,
        source_reference="Existing CarbonCoach V1 local passenger-distance coefficient.",
    ),
    "goods.coffee_serving": FallbackFactor(
        key="goods.coffee_serving",
        name="prepared coffee beverage serving",
        category="goods_services",
        dimension="number",
        amount_parameter="number",
        unit_parameter="number_unit",
        unit="item",
        kg_co2e_per_unit=0.25,
        confidence=0.55,
        source_reference="Maintained bootstrap coffee-serving pathway; excludes delivery travel.",
    ),
    "goods.beef_burrito_serving": FallbackFactor(
        key="goods.beef_burrito_serving",
        name="beef burrito serving",
        category="goods_services",
        dimension="number",
        amount_parameter="number",
        unit_parameter="number_unit",
        unit="item",
        kg_co2e_per_unit=2.0,
        confidence=0.50,
        source_reference="Maintained bootstrap beef-meal serving pathway; excludes drinks and delivery travel.",
    ),
    "goods.burger_serving": FallbackFactor(
        key="goods.burger_serving",
        name="burger serving",
        category="goods_services",
        dimension="number",
        amount_parameter="number",
        unit_parameter="number_unit",
        unit="item",
        kg_co2e_per_unit=2.5,
        confidence=0.48,
        source_reference="Maintained bootstrap burger-serving pathway; excludes sides, drinks, and delivery travel.",
    ),
    "goods.fries_serving": FallbackFactor(
        key="goods.fries_serving",
        name="fries serving",
        category="goods_services",
        dimension="number",
        amount_parameter="number",
        unit_parameter="number_unit",
        unit="item",
        kg_co2e_per_unit=0.55,
        confidence=0.45,
        source_reference="Maintained bootstrap fries-serving pathway; excludes delivery travel.",
    ),
    "goods.pizza_serving": FallbackFactor(
        key="goods.pizza_serving",
        name="pizza serving",
        category="goods_services",
        dimension="number",
        amount_parameter="number",
        unit_parameter="number_unit",
        unit="item",
        kg_co2e_per_unit=1.8,
        confidence=0.45,
        source_reference="Maintained bootstrap pizza-serving pathway; excludes delivery travel.",
    ),
    "goods.sandwich_serving": FallbackFactor(
        key="goods.sandwich_serving",
        name="sandwich serving",
        category="goods_services",
        dimension="number",
        amount_parameter="number",
        unit_parameter="number_unit",
        unit="item",
        kg_co2e_per_unit=1.2,
        confidence=0.45,
        source_reference="Maintained bootstrap sandwich-serving pathway; excludes drinks and delivery travel.",
    ),
    "goods.beef_weight": FallbackFactor(
        key="goods.beef_weight",
        name="purchased beef by mass",
        category="goods_services",
        dimension="weight",
        amount_parameter="weight",
        unit_parameter="weight_unit",
        unit="kg",
        kg_co2e_per_unit=27.0,
        confidence=0.55,
        source_reference="Maintained bootstrap beef-mass pathway.",
    ),
    "goods.soft_drink_serving": FallbackFactor(
        key="goods.soft_drink_serving",
        name="soft drink serving",
        category="goods_services",
        dimension="number",
        amount_parameter="number",
        unit_parameter="number_unit",
        unit="item",
        kg_co2e_per_unit=0.25,
        confidence=0.45,
        source_reference="Maintained bootstrap soft-drink serving pathway; excludes delivery travel.",
    ),
    "goods.milk_item": FallbackFactor(
        key="goods.milk_item",
        name="retail milk item",
        category="goods_services",
        dimension="number",
        amount_parameter="number",
        unit_parameter="number_unit",
        unit="item",
        kg_co2e_per_unit=1.2,
        confidence=0.42,
        source_reference="Maintained bootstrap grocery item pathway for milk; exact container size is not inferred.",
    ),
    "goods.bread_item": FallbackFactor(
        key="goods.bread_item",
        name="bread item",
        category="goods_services",
        dimension="number",
        amount_parameter="number",
        unit_parameter="number_unit",
        unit="item",
        kg_co2e_per_unit=0.7,
        confidence=0.42,
        source_reference="Maintained bootstrap grocery item pathway for bread; exact loaf weight is not inferred.",
    ),
    "goods.snack_serving": FallbackFactor(
        key="goods.snack_serving",
        name="snack item",
        category="goods_services",
        dimension="number",
        amount_parameter="number",
        unit_parameter="number_unit",
        unit="item",
        kg_co2e_per_unit=0.4,
        confidence=0.40,
        source_reference="Maintained bootstrap grocery snack pathway; product mix remains approximate.",
    ),
    "waste.recycling_plastic": FallbackFactor(
        key="waste.recycling_plastic",
        name="plastic recycling by mass",
        category="waste",
        dimension="weight",
        amount_parameter="weight",
        unit_parameter="weight_unit",
        unit="kg",
        kg_co2e_per_unit=0.021,
        confidence=0.55,
        source_reference="Maintained bootstrap recycling pathway for plastic mass only.",
    ),
    "waste.recycling_cardboard": FallbackFactor(
        key="waste.recycling_cardboard",
        name="cardboard recycling by mass",
        category="waste",
        dimension="weight",
        amount_parameter="weight",
        unit_parameter="weight_unit",
        unit="kg",
        kg_co2e_per_unit=0.05,
        confidence=0.55,
        source_reference="Maintained bootstrap recycling pathway for cardboard mass only.",
    ),
    "waste.recycling_paper": FallbackFactor(
        key="waste.recycling_paper",
        name="paper recycling by mass",
        category="waste",
        dimension="weight",
        amount_parameter="weight",
        unit_parameter="weight_unit",
        unit="kg",
        kg_co2e_per_unit=0.04,
        confidence=0.52,
        source_reference="Maintained bootstrap recycling pathway for paper mass only.",
    ),
    "waste.recycling_glass": FallbackFactor(
        key="waste.recycling_glass",
        name="glass recycling by mass",
        category="waste",
        dimension="weight",
        amount_parameter="weight",
        unit_parameter="weight_unit",
        unit="kg",
        kg_co2e_per_unit=0.03,
        confidence=0.52,
        source_reference="Maintained bootstrap recycling pathway for glass mass only.",
    ),
    "waste.recycling_metal": FallbackFactor(
        key="waste.recycling_metal",
        name="metal recycling by mass",
        category="waste",
        dimension="weight",
        amount_parameter="weight",
        unit_parameter="weight_unit",
        unit="kg",
        kg_co2e_per_unit=0.02,
        confidence=0.52,
        source_reference="Maintained bootstrap recycling pathway for metal mass only.",
    ),
    "waste.composting_food": FallbackFactor(
        key="waste.composting_food",
        name="food scraps composting by mass",
        category="waste",
        dimension="weight",
        amount_parameter="weight",
        unit_parameter="weight_unit",
        unit="kg",
        kg_co2e_per_unit=0.1,
        confidence=0.55,
        source_reference="Maintained bootstrap composting pathway for food-waste mass only.",
    ),
    "waste.landfill_general": FallbackFactor(
        key="waste.landfill_general",
        name="general landfill waste by mass",
        category="waste",
        dimension="weight",
        amount_parameter="weight",
        unit_parameter="weight_unit",
        unit="kg",
        kg_co2e_per_unit=0.5,
        confidence=0.50,
        source_reference="Maintained bootstrap landfill pathway for weighed general or mixed packaging waste.",
    ),
    "waste.landfill_plastic": FallbackFactor(
        key="waste.landfill_plastic",
        name="plastic landfill waste by mass",
        category="waste",
        dimension="weight",
        amount_parameter="weight",
        unit_parameter="weight_unit",
        unit="kg",
        kg_co2e_per_unit=0.12,
        confidence=0.48,
        source_reference="Maintained bootstrap landfill pathway for weighed plastic waste only.",
    ),
    "waste.landfill_cardboard": FallbackFactor(
        key="waste.landfill_cardboard",
        name="cardboard landfill waste by mass",
        category="waste",
        dimension="weight",
        amount_parameter="weight",
        unit_parameter="weight_unit",
        unit="kg",
        kg_co2e_per_unit=0.32,
        confidence=0.48,
        source_reference="Maintained bootstrap landfill pathway for weighed cardboard waste only.",
    ),
    "waste.landfill_paper": FallbackFactor(
        key="waste.landfill_paper",
        name="paper landfill waste by mass",
        category="waste",
        dimension="weight",
        amount_parameter="weight",
        unit_parameter="weight_unit",
        unit="kg",
        kg_co2e_per_unit=0.38,
        confidence=0.48,
        source_reference="Maintained bootstrap landfill pathway for weighed paper waste only.",
    ),
    "waste.landfill_food": FallbackFactor(
        key="waste.landfill_food",
        name="food waste landfill by mass",
        category="waste",
        dimension="weight",
        amount_parameter="weight",
        unit_parameter="weight_unit",
        unit="kg",
        kg_co2e_per_unit=0.75,
        confidence=0.48,
        source_reference="Maintained bootstrap landfill pathway for weighed food waste only.",
    ),
}
